name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # Install dependencies
      - run: bundle install

      # Build the site
      - run: cd wedding_web && bundle exec jekyll build --destination ../_site

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
